export const START_FETCHING_DISCOUNT = '[DISCOUNT] START_FETCHING_DISCOUNT';
export const FETCHED_DISCOUNT = '[DISCOUNT] FETCHED_DISCOUNT';
export const ERROR_FETCHING_DISCOUNT = '[DISCOUNT] ERROR_FETCHING_DISCOUNT';
